apiVersion: apps/v1
kind: Deployment
metadata: 
  name: platforms-depl
specs:
  replicas: 1
  selector:
    matchLables:
      app: platformservice
  template:
    metadata:
      lables:
        app: platformservice
    spec:
      containers:
        - name: platformservice
          image: andraderodrigosilva/platformservice:latest